# Generated by Django 4.1.3 on 2022-11-08 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="아이디",
                    ),
                ),
                ("body", models.CharField(max_length=512, verbose_name="댓글")),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="아이디",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="블로그 제목")),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post",
                        to="post.comment",
                    ),
                ),
            ],
        ),
    ]
