# Generated by Django 4.1.3 on 2022-11-17 05:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("post", "0002_post_like_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="like_member",
            field=models.ManyToManyField(
                blank=True, related_name="like_post", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]